### ISSUE TITLE
Cannot find modules after npm install 

### ISSUE THREAD

**Issue by teddyding** [mbasso/react-http-request#1]
Hi,

I'm using a React+Webpack and after I run "npm install --save react-http-request", "react-http-request": "^1.0.2" shows up in the dependencies in my package.json. But when I do npm run build, I get an error saying cannot find module "react-http-request". Any hint on why this happens?

Thanks!

**Comment by mbasso** [comment]
Hi @kn1ghtted,
could you please try doing the following?
- delete `node_modules` folder
- run `npm install`
- run `npm run build`

If the error persists, could you provide the content of that error message?
Thanks

**Comment by mbasso** [comment]
Hi @kn1ghtted,
have you solved the problem? Can I close this issue?

**Comment by teddyding** [comment]
Yes! Thanks a lot for the response.

On Aug 4, 2016, at 12:06 AM, Matteo Basso <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @kn1ghttedhttps://github.com/kn1ghtted,
have you solved the problem? Can I close this issue?

##
