### ISSUE TITLE
setState outside componentWillMount

### ISSUE THREAD

**Issue by pungggi** [mbasso/react-http-request#4]
Warning: setState(...): Can only update a mounting component. This usually means you called setS
tate() outside componentWillMount() on the server. This is a no-op. Please check the code for th
e Request component.

**Comment by mbasso** [comment]
Hi @pungggi,
thank you for opening this issue.
Can you please provide a snippet of code (if possible) or additional information that might be useful for the resolution?
I'll check the problem this night and I'll contact you as soon as possible

**Comment by mbasso** [comment]
I took a look at the problem, are you implementing server-side rendering to handle the initial render?

**Comment by pungggi** [comment]
Hello yes i am using nextjs

Am 26.02.2017 8:01 nachm. schrieb "Matteo Basso" <notifications@github.com>:

**Comment by mbasso** [comment]
I think that `react-http-request` makes an async API call that is not handled during the server-side rendering.
As explained [here](https://zeit.co/blog/next#data-fetching-is-up-to-the-developer) nextjs makes an extension to the React's Component with `getInitialProps` to handle this situations.
I think that the initial server rendering might use that extension and `react-http-request` might be use only client-side. So, you can recognize the situation as shown in the gif in [this](https://zeit.co/blog/next) page and act accordingly.

If you prefer, I can also add a new optional prop to the component for preloaded data, as explained [here](http://stackoverflow.com/questions/20815423/how-to-render-asynchronously-initialized-components-on-the-server?answertab=votes#tab-top). Please, let me know if this might be useful.

If you have other ideas about that, please also let me know.
I hope this will help you

**Comment by pungggi** [comment]
hi thank you, it is server rendered yes.

What do you mean by acting accordingly.

**Comment by mbasso** [comment]
I've never used nextjs in production, but I think that we can use `getInitialProps` and `react-http-request` based on the situation.
Basically we can use `getInitialProps` to get the initial information used to show the page and `react-http-request` to perform dynamic operations.
For example, if we always want to show the information of a github account, we can always fetch them in `getInitialProps`.
But, if we want to show some additional information after that a button has been clicked, for example, we can render a `Request` component that shows a loader and then the data.
This is a node that cannot be rendered by the server because is consequent to a user action, so `getInitialProps` is not useful in this case.

What I meant in the previous comment is that we can also recognize if the page is server-rendered or client-rendered, so, we can perform different actions based on this information.
This can be useful in some cases.


Here is some example code:

```js
import React from 'react'
import Request from 'react-http-request'
import ComponentThatUsesData from './ComponentThatUsesData'
import { apiURL, apiClientURL } from '../api';
import 'isomorphic-fetch'

export default class extends React.Component {

  static async getInitialProps ({ req }) {
    // fetch initial data that must always be shown
    const res = await fetch('https://api.github.com/users/mbasso')
    const data = await res.json()
    
    // req is defined if the page is server-rendered
    const server = req ? true : false;
    // perform server actions
    if (server) {
      // do stuff
    }

    return {
      data,
      server,
    };
  }

  state = {
    clicked: false,
  }

  onButtonClick = () => {
    this.setState({
      clicked: true,
    });
  }

  render() {
    const { data, server } = this.props;
    const { clicked } = this.state;
    return (
      <div>
        <h2>User info</h2>
        <p>
          Name: {data.name}
          Company: {data.company}
          Blog: {data.blog}
          Location: {data.location}
        </p>
        <button onClick={this.onButtonClick}>
          Click me!
        </button>
        { /* show additional info only if clicked is true */ }
        {
          clicked && (
            <Request url={apiURL}>
              {
                ({ error, result, loading }) => {
                  let result;
                  if (loading) {
                    result = 'loading...';
                  } else if (error) {
                    result = 'An error has occurred';
                  } else {
                    result = <ComponentThatUsesData data={result.body} />;
                  }
                }
              }
            </Request>
          )
        }
        {
          /*
            perform actions like send client data to the server
            and so on
          */
        }
        {
          !server && (
            <Request
              url={apiClientURL}
              method="post"
              send={clientData}
            >
              {
                ({ error, result, loading }) => {
                  // do stuff
                }
              }
            </Request>
          )
        }
      </div>
    );
  }

}
```

**Comment by pungggi** [comment]
this is exactly how it should work, so no need alter react-http-request. thank you for the example

**Comment by mbasso** [comment]
you're welcome!
