### ISSUE TITLE
Access data from Express server and render by React

### ISSUE THREAD

**Issue by 0xTheProDev** [mbasso/react-http-request#5]
**Abstract**
I am trying to get some JSON formatted data from my Express app in backend side and render them using React Components.

**Steps to reproduce**
1. Created a component which renders a listData specified in state property.
2. Created another component that implements react-http-request to form a request to server.
3. Get the data from second and inject to first one.

**Problem**
Can't find a way to perform the third step (or it's equivalent).

**Comment by mbasso** [comment]
Hi @Progyan1997,
I'm not completely sure that I've undestand what you mean, could you please paste here some example code?
If I've understand correctly, you can use both state and api data in this way:

```js
import React from 'react';
import Request from 'react-http-request';
import { useData } from './utils';

export default class App extends React.Component {

  state = {
    data: {},
  }

  render() {
    return (
      <Request
        url='https://api.github.com/users/mbasso'
        method='get'
        accept='application/json'
        verbose
      >
        {
          ({error, result, loading}) => {
            if (loading) {
              return <div>loading...</div>;
            } else if (error) {
              return <div>error</div>;
	    } else {
	      // result.body contains the response
              const jsonData = result.body;
	      // here you can use data as you prefer
              useData(jsonData);
	      // and here you can return a component or null
	      return (
                  <FirstComponent
                      stateData={this.state.data}
                      apiData={jsonData}
                  />
              );
            }
          }
        }
      </Request>
    );
  }
}
```

**Comment by mbasso** [comment]
@Progyan1997 did you solve the problem?
Can I close this issue?

**Comment by 0xTheProDev** [comment]
I didn't try it, so can't say for sure that this will work in my environment.
Rather I would like to ask if it is possible to inject data-dependency in React component hierarchy, like following:
(Page) --> (Tab) --> (Table) --> (Row) --> (Action Btn)
I am supposed to knock the API while loading the page, and get an array of JSON objects which I will print in each row depending upon some parameters. When the Button on a row is clicked, it is required to set another request (asking for deletion for example) on the data specified in row.

**Comment by mbasso** [comment]
Basically you need to call an api from a leaf component (Action Btn) of your tree and notify the changes to a component on the top of this tree (Page, Tab or Table) right?
In this way the root component will delete the row that perform the action since the corresponding element will miss in the array.

I think that your first request should save its result in the state (using [redux](https://github.com/reactjs/redux), [mobx](https://github.com/mobxjs/mobx), or something else) and the second request should update the state (deleting the element for example).
This is the only way that allows leaf components to update the data. In our case, delete, update and create new rows. Are you already using one of these libraries?

**Comment by 0xTheProDev** [comment]
I am a complete newbie in React Domain, so I haven't used any of the frameworks you mentioned. But thanks for your support, I guess I got what I need.
Moreover, how can I get to you later on if I needed _(personally)_? Are you active on @gitter or something?

**Comment by mbasso** [comment]
You're welcome!
yes, I'm signed up on [gitter](https://gitter.im) with this github account, you can contact me there if you need some help
